# Exported from Render on 2025-12-07T06:51:16Z
version: "1"
services:
  - type: web
    name: min-monorepo-be
    runtime: python
    repo: https://github.com/annnnangan/min-monorepo
    plan: free
    envVars:
      - key: PORT
        value: "10000"
      - key: ENV
        value: "production"
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: min-monorepo-fe
          property: url
    region: singapore
    buildCommand: uv sync --no-dev
    startCommand: uv run main.py
    autoDeployTrigger: commit
    rootDir: backend
  - type: web
    name: min-monorepo-fe
    runtime: static
    repo: https://github.com/annnnangan/min-monorepo
    buildCommand: npm run build
    staticPublishPath: dist
    autoDeployTrigger: commit
    rootDir: frontend
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: min-monorepo-be
          property: url
